# -*- coding: utf-8 -*-
"""SelectionSort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10V-RvUONlT9Kfigat_rs6YPJO3zooHkh
"""

def selection_sort(arr, idx=0):

  if idx < len(arr):
    min_idx = idx
    for i in range(idx + 1, len(arr)):
      if arr[i] < arr[min_idx]:
        min_idx = i

    arr[idx], arr[min_idx] = arr[min_idx], arr[idx]

    selection_sort(arr, idx + 1)

  return arr


  a = [1, 5 , 4 , 74, 100, 15, 44, 61, 3]
  print(selection_sort(a))